name: build and release angle libraries

on:
  push:
    branches:
      - '*'

jobs:
  windows:
    strategy:
      matrix:
        arch: [amd64, 386]
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: download tash
        shell: bash
        run: |
          env GOPATH=`pwd`/gopath go get github.com/uiez/tash
          mv ./gopath/bin/tash.exe .
          rm -rf ./gopath
      - name: build angle
        shell: bash
        run: ./tash.exe lib -a "BUILD_ARCH=${{matrix.arch}}"
      - name: save artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows-${{matrix.arch}}
          path: vcpkg/libs

  release:
    runs-on: ubuntu-18.04
    needs: [windows]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: download artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: release libraries
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          assets=()
          for asset in `find artifacts -type f`; do
            assets+=("-a" "$asset")
          done
          hub release create "${assets[@]}" -m build-${GITHUB_SHA::12} -t ${GITHUB_SHA} build-${GITHUB_SHA::12}
